channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - cython
  - ipython
  - ipyparallel
  - ipywidgets
  - numpy
  - matplotlib
  - mpi4py
  - networkx
  - pandas
  - scikit-image
  - scikit-learn
  - sympy
  - plotly
  - seaborn
  - pytorch-cpu
  - torchvision-cpu
  - pip
  - pip:
    - torchaudio
    - japanize-matplotlib
    - pydotplus
    - pydot
    - tensorflow
