name: env_jupyter
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - numpy
  - sympy
  - scipy
  - matplotlib
  - plotly
  - scikit-learn
  - pandas
  - seaborn
  - networkx
  - ipywidgets
  - pytorch
  - nodejs
  - pip 
  - pip:
    - japanize-matplotlib
    - pydotplus
    - pydot
    - jupyterlab_widgets
