name: ritmath-22ds2
channels:
  - anaconda
  - conda-forge
  - pytorch
dependencies:
- python=3.8
- numpy
- scipy
- pandas
- matplotlib
- plotly
- seaborn
- scikit-learn
- ipython
- notebook
- pytorch-cpu
- torchvision-cpu
- opencv
- pillow
- ipython
- cython
- networkx
- scikit-image
- sympy
- pip
- pip:
    - torchaudio
    - japanize-matplotlib
    - pydotplus
    - pydot
    - tensorflow
